[package]
name = "sequence_beans"
version = "0.0.1"
edition = "2021"

[lib]
name = "sequence_bean"
path = "src/lib.rs"
test = true

[[bin]]
name = "sequence_beans"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
